### ISSUE TITLE
Send results back

### ISSUE THREAD

**Issue by GoldsteinE** [williamjameshandley/vimteractive#10]
It'd be cool if there was possibility to send large command results to Vim in convenient way (e. g. opening for them new buffer). Use case: Python command generated a large JSON, we want to edit it it Vim and load back to interactive console.

**Comment by williamjameshandley** [comment]
In theory the interface could be very intuitive (i.e. ctrl-S in a terminal buffer sends to a new 'data buffer'). In practice I imagine the implementation will be different for each REPL, and therefore this would represent a very large project.

**Comment by GoldsteinE** [comment]
It can be done more easily if we use not hotkey, but some IPC method for that (writing to file/fd?). Hotkey is also possible if we know how REPL prompt looks like.

**Comment by williamjameshandley** [comment]
I'm afraid that's a little out of my area of expertise (what does IPC stand for?), but it sounds like a good idea. It might be worth looking at [vim-ipython](https://github.com/ivanov/vim-ipython), which does have this functionality, although it's likely very python-specific. (vim-ipython was my original inspiration for this package, trying to bring out the essential elements so that we could generalise to other REPLs)
