### ISSUE TITLE
Possible errors in autoload/vimteractive.vim

### ISSUE THREAD

**Issue by fruzsinaagocs** [williamjameshandley/vimteractive#11]
## Problem description

Having installed vimteractive with the native package manager (vim 8+), with a working `:help vimteractive` to verify the installation, I get the following error when running `:Iipython` or any other vimteractive command (`:I*`):

![Screenshot from 2019-09-09 15-00-59](https://user-images.githubusercontent.com/19972401/64537465-c5a04d80-d312-11e9-9bb9-9e0c8c41114c.png)

## Setup

- ubuntu 18.04.3
- vim 8.0.1453

## A solution?

The errors seemed to be in `autoload/vimteractive.vim`. 
1. First (and this may be wrong), I don't think vim script supports default values of arguments like `bufname = ''`. I changed this to just `bufname` in the relevant line, which seemed to have made the first error disappear.
2. `term_kill` wasn't actually used in its enclosing function, so I just deleted the line it appeared in.

After these changes, vimteractive seemed to be working again, but I haven't tried any of the new features of version 2.0.

**Comment by williamjameshandley** [comment]
Many thanks for this @fruzsinaagocs . I think I have seen similar behaviour on other machines that I work on. It is likely due to differences in vim version 8.0 and 8.1 (I have 8.1 on my machine). Ideally it should work for both.

>First (and this may be wrong), I don't think vim script supports default values of arguments like bufname = ''. I changed this to just bufname in the relevant line, which seemed to have made the first error disappear.

I don't think `connect` is ever used without an argument, so I believe this change should fix the issue. @GoldsteinE should weigh in on this if I'm wrong though. Does `:Iterm` work if you've made this change?

>term_kill wasn't actually used in its enclosing function, so I just deleted the line it appeared in.

This may also be a difference between 8.1 and 8.0. If there's no change in functionality then I don't see any problem with removing it, although it may be related to @GoldsteinE  's change that makes sure the terminal shuts down gracefully.

Please submit a pull request and I'll try it out on my machine to see if everything is behaving as it should.

**Comment by fruzsinaagocs** [comment]
I'll submit a PR shortly!

**Comment by williamjameshandley** [comment]
Ah, actually in using it on another machine, I've noticed that the default argument was doing something important. Are you able to create a similar branch between vim versions which puts in a default argument for bufname for vim > 8.1 ?

**Comment by fruzsinaagocs** [comment]
I did something different that hopefully works across versions, see the fresh PR.

**Comment by fruzsinaagocs** [comment]
What was the important thing that the default argument did?

**Comment by williamjameshandley** [comment]
It meant that if only one terminal is open, if you ran `:Iconn` without any arguments then it would automatically connect to the only available terminal.

**Comment by williamjameshandley** [comment]
@fruzsinaagocs Has this issue been resolved by #13 and #12 ?

**Comment by fruzsinaagocs** [comment]
Yes, this issue can be closed now.
