### ISSUE TITLE
Can't backspace up to previous line in Insert mode

### ISSUE THREAD

**Issue by tom-andersson** [williamjameshandley/vimteractive#25]
In an `:Iipython` session, I can't use backspace to bring my cursor on line `n` (and the remaining text) up to line `n-1` (say after accidentally pressing `Enter`). I can re-combine lines in (e.g. with `C-J`), but it's a bit more effort. 

P.S. Thanks very much for making `vimteractive`!

**Comment by williamjameshandley** [comment]
Hi @tom-andersson . 

Does this issue occur in the terminal window, or in the python file buffer? I'm trying to work out whether this is due to vimteractive or the behaviour of the vim terminal (in which case, that's may be just how the vim terminal works (``:help terminal``), all vimteractive does is just wrap around the that functionality).

**Comment by tom-andersson** [comment]
Thanks for getting back to me @williamjameshandley. I'm getting this behaviour in the Python file buffer. I'm having the issue on a remote machine which uses Vim 8.1.1, but on my local machine with Vim 8.0.1453 the backspace up to a new line works.

**Comment by williamjameshandley** [comment]
This sounds like very unusual behaviour. I'm struggling to see how vimteractive could be affecting this. Could it be an interaction with another plugin? If you disable the other plugins and only have vimteractive installed do you still see this effect?
