### ISSUE TITLE
+terminal

### ISSUE THREAD

**Issue by bjarthur** [williamjameshandley/vimteractive#30]
might add to the README to indicate this flag is needed when vim is compiled.  i got this error using vim version 8.0.1283  on OS X:

```
Error detected while processing function vimteractive#term_start:
line    2:
Your version of vim is not compiled with +terminal. Cannot use vimteractive
Press ENTER or type command to continue
```

**Comment by williamjameshandley** [comment]
Hi @bjarthur -- many thanks for this observation. Feel free to submit a PR with the added sentences to the README and vim documents., although I believe the error message that vimteractive produces is informative enough for this to be a 'desirable' rather than 'required' PR. Did you manage to recompile your vim with +terminal? in which case, instructions for this could also be added to the readme.
